// src/app/layout.js
import './globals.css';
import './common.css';
import { Providers } from './providers';

// Add metadata here (good for SEO, works in Server Components)
export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>  
          {children}
        </Providers>
      </body>
    </html>
  );
}